In [1]:
import pandas as pd
df = pd.read_csv('heart.csv')
df.head()
df = df[df.RestingBP != 0]
df = df[df.Cholesterol != 0]
df.Oldpeak=df.Oldpeak*10
#making bins
agegrp= pd.cut(df.Age,bins=[20,29,39,49,59,69,79],labels=["20s","30s","40s","50s","60s","70s"])
df.insert(1,"Age_Group",agegrp)
rbp= pd.cut(df.RestingBP,bins=[0,119,129,139,1000],labels=["Normal","Elevated","High","Extreme"])
df.insert(5,"Blood_Pressure_Level",rbp)
op= pd.cut(df.Oldpeak,bins=[-10,20,1000],labels=["Normal","Risk"])
df.insert(12,"Oldpeak_Level",op)
mHR= pd.cut(df.MaxHR,bins=[60,79,99,119,139,159,179,199,219],labels=["60-79","80-99","100-119","120-139","140-159","160-179","180-199","200-220"])
df.insert(10,"Max_Heart_Rate",mHR)
ch= pd.cut(df.Cholesterol,bins=[0,199,240,1000],labels=["<200","200-240",">240"])
df.insert(7,"Cholestrol_levels",ch)

df.describe()
df=df[df.Sex=="M"]
df

,Age,Age_Group,Sex,ChestPainType,RestingBP,Blood_Pressure_Level,Cholesterol,Cholestrol_levels,FastingBS,RestingECG,MaxHR,Max_Heart_Rate,ExerciseAngina,Oldpeak,Oldpeak_Level,ST_Slope,HeartDisease
0,40,40s,M,ATA,140,Extreme,289,>240,0,Normal,172,160-179,N,0.0,Normal,Up,0
2,37,30s,M,ATA,130,High,283,>240,0,ST,98,80-99,N,0.0,Normal,Up,0
4,54,50s,M,NAP,150,Extreme,195,<200,0,Normal,122,120-139,N,0.0,Normal,Up,0
5,39,30s,M,NAP,120,Elevated,339,>240,0,Normal,170,160-179,N,0.0,Normal,Up,0
7,54,50s,M,ATA,110,Normal,208,200-240,0,Normal,142,140-159,N,0.0,Normal,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911,59,50s,M,ASY,164,Extreme,176,<200,1,LVH,90,80-99,N,10.0,Normal,Flat,1
913,45,40s,M,TA,110,Normal,264,>240,0,Normal,132,120-139,N,12.0,Normal,Flat,1
914,68,60s,M,ASY,144,Extreme,193,<200,1,Normal,141,140-159,N,34.0,Risk,Flat,1
915,57,50s,M,ASY,130,High,131,<200,0,Normal,115,100-119,Y,12.0,Normal,Flat,1
917,38,30s,M,NAP,138,High,175,<200,0,Normal,173,160-179,N,0.0,Normal,Up,0

In [2]:
pd.set_option('display.max_rows',None)

In [12]:
#BHAVISH CELL
table = pd.crosstab([df.ST_Slope,df.ChestPainType,df.Max_Heart_Rate],df.ExerciseAngina,normalize='index')
table

ExerciseAngina                                N         Y
ST_Slope ChestPainType Max_Heart_Rate
Down     ASY           60-79           1.000000  0.000000
                       80-99           0.000000  1.000000
                       100-119         0.000000  1.000000
                       120-139         0.000000  1.000000
                       140-159         0.111111  0.888889
         ATA           160-179         1.000000  0.000000
         NAP           120-139         1.000000  0.000000
                       140-159         1.000000  0.000000
                       180-199         1.000000  0.000000
         TA            100-119         1.000000  0.000000
                       140-159         1.000000  0.000000
Flat     ASY           60-79           1.000000  0.000000
                       80-99           0.100000  0.900000
                       100-119         0.228070  0.771930
                       120-139         0.236111  0.763889
                       140-159         0.230769  0.769231
                       160-179         0.888889  0.111111
                       180-199         1.000000  0.000000
         ATA           80-99           0.000000  1.000000
                       100-119         1.000000  0.000000
                       120-139         0.500000  0.500000
                       140-159         0.571429  0.428571
                       160-179         0.750000  0.250000
                       180-199         1.000000  0.000000
         NAP           80-99           0.500000  0.500000
                       100-119         0.000000  1.000000
                       120-139         0.250000  0.750000
                       140-159         0.562500  0.437500
                       160-179         1.000000  0.000000
                       180-199         1.000000  0.000000
         TA            100-119         0.000000  1.000000
                       120-139         1.000000  0.000000
                       140-159         0.666667  0.333333
                       160-179         1.000000  0.000000
                       180-199         0.666667  0.333333
Up       ASY           80-99           0.500000  0.500000
                       100-119         0.444444  0.555556
                       120-139         0.666667  0.333333
                       140-159         0.750000  0.250000
                       160-179         0.666667  0.333333
                       180-199         0.800000  0.200000
         ATA           80-99           1.000000  0.000000
                       100-119         1.000000  0.000000
                       120-139         0.909091  0.090909
                       140-159         1.000000  0.000000
                       160-179         0.925926  0.074074
                       180-199         1.000000  0.000000
                       200-220         1.000000  0.000000
         NAP           80-99           0.500000  0.500000
                       100-119         1.000000  0.000000
                       120-139         0.923077  0.076923
                       140-159         0.857143  0.142857
                       160-179         0.962963  0.037037
                       180-199         1.000000  0.000000
         TA            120-139         0.857143  0.142857
                       140-159         1.000000  0.000000
                       160-179         0.750000  0.250000

In [59]:
#BHAVISH CELL
table = pd.crosstab([df.ST_Slope],df.HeartDisease,normalize='index')
table

HeartDisease         0         1
ST_Slope
Down          0.236842  0.763158
Flat          0.137324  0.862676
Up            0.826446  0.173554

In [ ]:
[[[0.071429,	0.928571],[0.075000,	0.925000],[0.600000,	0.400000]],[[0.500000,	0.500000],[0.315789,	0.684211],[0.965116,	0.034884]],[[0.800000,	0.200000],[0.250000,	0.750000],[0.937500,	0.062500]],[[0.666667,	0.333333],[0.352941,	0.647059],[0.750000,	0.250000]]]